### ISSUE TITLE
Need support for background images

### ISSUE THREAD

**Issue by ateev** [loktar00/react-lazy-load#44]
First of all, Great package. Currently this module supports only image tags. Can we please make it work for background-images too ? That would be really helpful.

**Comment by sergeylaptev** [comment]
Hello, @ateev. It works with any type of content. Can you describe your case in more detail?

**Comment by ateev** [comment]
Hey @sergeylaptev . I have a div with background-image set. To be exact, i'm looking for this functionality. http://dinbror.dk/blog/blazy/?ref=demo-page#Background

**Comment by sergeylaptev** [comment]
Here is the possible solution:
```jsx
<div className="MyComponent-container">
  <LazyLoad>
    <div
      className="MyComponent-containerImage"
      style={{ backgroundImage: 'url("http://apod.nasa.gov/apod/image/1502/HDR_MVMQ20Feb2015ouellet1024.jpg")' }}
    />
  </LazyLoad>
</div>
```

```css
@component MyComponent {
  @descendent container {
    position: relative;
    height: 700px;
  }

  @descendent containerImage {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
  }
}
```
