### ISSUE TITLE
Not responsive

### ISSUE THREAD

**Issue by Cam** [loktar00/react-lazy-load#61]
With the requirement of a fixed height setting, this plugin fails to work inside modern apps where responsive layouts are a standard requirement.

**Comment by ganmor** [comment]
You can specify a height in percentage

**Comment by jwilkinson** [comment]
That doesn't make it responsive, that makes is a % of the container height, whereas the image width is 100% is what dictates its height of auto.

**Comment by ctrlplusb** [comment]
Instead of just `height` could you not expose a `className` and/or `style`?

**Comment by xims** [comment]
Is there any solution for this yet?
Thanks!

**Comment by stereobooster** [comment]
It should take ratio and calculate height based on width of component. Like [responsive embed in foundation](http://foundation.zurb.com/sites/docs/responsive-embed.html).

**Comment by stereobooster** [comment]
Here is the solution

```js
<LazyLoad className="responsive">
  <img src='http://apod.nasa.gov/apod/image/1502/HDR_MVMQ20Feb2015ouellet1024.jpg' alt='' width="1024" height="762" />
</LazyLoad>
```

```css
.responsive {
  position: relative;
  height: 0;
  padding-bottom: 75%;
  overflow: hidden;
}

.responsive iframe,
.responsive object,
.responsive embed,
.responsive video,
.responsive img {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
```
